# Generated by Django 3.2 on 2023-04-25 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20230423_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites_list',
            new_name='Favorite',
        ),
    ]
