# Generated by Django 3.2 on 2023-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_description_recipe_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
